"""add model media

Revision ID: eedb6879caf5
Revises: a58fc7702fbb
Create Date: 2024-03-04 20:26:30.614181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eedb6879caf5'
down_revision: Union[str, None] = 'a58fc7702fbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('file_format', sa.String(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name='fk_media_created_by', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_table('category',
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('logo_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('sort > 0', name='check_sort_positive'),
    sa.ForeignKeyConstraint(['logo_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('category_translation',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('desc', sa.String(), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'language_id')
    )
    op.create_index(op.f('ix_category_translation_desc'), 'category_translation', ['desc'], unique=False)
    op.create_index(op.f('ix_category_translation_title'), 'category_translation', ['title'], unique=False)
    op.create_table('course_lesson_media',
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('course_lesson_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_lesson_id'], ['course_lesson.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('contact', sa.Column('image_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'contact', 'media', ['image_id'], ['id'])
    op.add_column('course', sa.Column('banner_image_id', sa.UUID(), nullable=True))
    op.add_column('course', sa.Column('banner_file_id', sa.UUID(), nullable=True))
    op.add_column('course', sa.Column('trailer_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'course', 'media', ['banner_file_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'course', 'media', ['banner_image_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'course', 'media', ['trailer_id'], ['id'], ondelete='CASCADE')
    op.add_column('course_lesson', sa.Column('video_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'course_lesson', 'media', ['video_id'], ['id'], ondelete='CASCADE')
    op.add_column('course_students_work_block', sa.Column('media_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'course_students_work_block', 'media', ['media_id'], ['id'], ondelete='CASCADE')
    op.add_column('file_block', sa.Column('media_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'file_block', 'media', ['media_id'], ['id'])
    op.add_column('language', sa.Column('flag_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'language', 'media', ['flag_id'], ['id'])
    op.add_column('link_category_course', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'link_category_course', 'category', ['category_id'], ['id'])
    op.add_column('mentor_info', sa.Column('resume_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'mentor_info', 'media', ['resume_id'], ['id'])
    op.add_column('organization', sa.Column('logo_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'organization', 'media', ['logo_id'], ['id'], ondelete='CASCADE')
    op.add_column('training', sa.Column('input_id', sa.UUID(), nullable=True))
    op.add_column('training', sa.Column('output_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'training', 'media', ['output_id'], ['id'])
    op.create_foreign_key(None, 'training', 'media', ['input_id'], ['id'])
    op.add_column('user', sa.Column('image_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_user_image', 'user', 'media', ['image_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_image', 'user', type_='foreignkey')
    op.drop_column('user', 'image_id')
    op.drop_constraint(None, 'training', type_='foreignkey')
    op.drop_constraint(None, 'training', type_='foreignkey')
    op.drop_column('training', 'output_id')
    op.drop_column('training', 'input_id')
    op.drop_constraint(None, 'organization', type_='foreignkey')
    op.drop_column('organization', 'logo_id')
    op.drop_constraint(None, 'mentor_info', type_='foreignkey')
    op.drop_column('mentor_info', 'resume_id')
    op.drop_constraint(None, 'link_category_course', type_='foreignkey')
    op.drop_column('link_category_course', 'category_id')
    op.drop_constraint(None, 'language', type_='foreignkey')
    op.drop_column('language', 'flag_id')
    op.drop_constraint(None, 'file_block', type_='foreignkey')
    op.drop_column('file_block', 'media_id')
    op.drop_constraint(None, 'course_students_work_block', type_='foreignkey')
    op.drop_column('course_students_work_block', 'media_id')
    op.drop_constraint(None, 'course_lesson', type_='foreignkey')
    op.drop_column('course_lesson', 'video_id')
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.drop_column('course', 'trailer_id')
    op.drop_column('course', 'banner_file_id')
    op.drop_column('course', 'banner_image_id')
    op.drop_constraint(None, 'contact', type_='foreignkey')
    op.drop_column('contact', 'image_id')
    op.drop_table('course_lesson_media')
    op.drop_index(op.f('ix_category_translation_title'), table_name='category_translation')
    op.drop_index(op.f('ix_category_translation_desc'), table_name='category_translation')
    op.drop_table('category_translation')
    op.drop_table('category')
    op.drop_table('media')
    # ### end Alembic commands ###
