"""migration

Revision ID: 161fb3b49a73
Revises: eedb6879caf5
Create Date: 2024-03-05 19:26:09.134397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '161fb3b49a73'
down_revision: Union[str, None] = 'eedb6879caf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discount',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('percent', sa.Float(), nullable=False),
    sa.Column('start', sa.Date(), nullable=False),
    sa.Column('stop', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('is_archive', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('0 < percent AND percent <= 100', name='check_percent'),
    sa.CheckConstraint('start < stop', name='check_start_stop_date'),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discount_translation',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('desc', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('discount_id', sa.UUID(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['discount_id'], ['discount.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discount_id', 'language_id')
    )
    op.add_column('course', sa.Column('discount_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'course', 'discount', ['discount_id'], ['id'])
    op.add_column('course_lesson', sa.Column('discount_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'course_lesson', 'discount', ['discount_id'], ['id'])
    op.add_column('course_module', sa.Column('discount_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'course_module', 'discount', ['discount_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course_module', type_='foreignkey')
    op.drop_column('course_module', 'discount_id')
    op.drop_constraint(None, 'course_lesson', type_='foreignkey')
    op.drop_column('course_lesson', 'discount_id')
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.drop_column('course', 'discount_id')
    op.drop_table('discount_translation')
    op.drop_table('discount')
    # ### end Alembic commands ###
